### ISSUE TITLE
Bad alignment for spinner when button is fullwidth

### ISSUE THREAD

**Issue by OlivierAlbertini** [VilledeMontreal/angular-ui#23]
![image](https://user-images.githubusercontent.com/3801683/155620628-04800c5d-c65a-4499-9bae-1125a88d2409.png)

## Reproduce in Storybook
```
fullWidth = true
loading = true
rightIcon = true or false
```

**Comment by OlivierAlbertini** [comment]
I don't see the use case here https://services.montreal.ca/boite-outils4/?p=viewall-components-buttons

**Comment by OlivierAlbertini** [comment]
for getting the right alignment, just add `btn-block` to a button with the loading, here :  https://services.montreal.ca/boite-outils4/?p=viewall-components-buttons

**Comment by sori-ard** [comment]
Je pense que le fix pour bao-icon a réglé cette problème aussi.
![Capture d’écran, le 2022-03-09 à 17 23 56](https://user-images.githubusercontent.com/74427984/157549212-7ed9e42b-8484-499b-b1d3-3889d9fe0ddb.png)

**Comment by MaudeLaflamme** [comment]
Testé de mon côté aussi et l'alignement est le bon depuis le build 41.

**Comment by OlivierAlbertini** [comment]
Je confirme aussi. Nice. Quelle PR l'a réglée ?

**Comment by sori-ard** [comment]
PR: https://github.com/VilledeMontreal/angular-ui/pull/40

**Comment by OlivierAlbertini** [comment]
Merci je ferme !
