### ISSUE TITLE
Ajouter l'icône de cellulaire (angular-ui)

### ISSUE THREAD

**Issue by gregpetit** [VilledeMontreal/angular-ui#81]
DCI a besoin d'un icône de cellulaire et cela manquait à notre librairie d'icône.
Lien vers la version Figma : https://www.figma.com/file/Ijmyha6Ag2VFZUmEBNBQXwpZ/VDM---Librairie?node-id=0%3A826
Le svg est dispo ici : https://drive.google.com/file/d/11sm2oUZ3xEGq4jvYbeWtRvkg4Ib8CQUu/view?usp=sharing

**Comment by OlivierAlbertini** [comment]
il reste à l'ajouter dans Angular 13 https://github.com/VilledeMontreal/angular-ui/pull/108 (seulement pour Angular 14)
