### ISSUE TITLE
Barre de navigation Service numérique - Logo et bouton Quitter

### ISSUE THREAD

**Issue by EliseMontreal** [VilledeMontreal/angular-ui#95]
### À faire
Le logo n'est plus un élément interactif.
Ajouter un texte hors écran pour le bouton Quitter en version Tablette et mobile

### Documentation
Specs : https://confluence.montreal.ca/pages/viewpage.action?pageId=158237293
Copydeck FR et EN : NAV-01 https://confluence.montreal.ca/display/BOPPN/_Copydeck+FR+et+EN

Contacter @gregpetit pour groomer la composante.

**Comment by gregpetit** [comment]
@EliseMontreal La composante n'existe pas encore dans la lib Angular alors vu que c'est dans les specs globales, cette fonctionnalité sera couverte lors du développement de la composante. Je vais donc supprimer cette issue.
